#!/usr/bin/env python3
"""PreToolUse hook: block direct edits to files that build.py generates."""
import fnmatch
import json
import os
import sys

GENERATED = ["index.html", "404.html", "sitemap.xml", "llms.txt", "*/index.html", "post/*/index.html"]

payload = json.load(sys.stdin)
path = payload.get("tool_input", {}).get("file_path", "")
root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
rel = os.path.relpath(os.path.abspath(path), root)

# fnmatch's * also matches "/", so check the segment count explicitly.
parts = rel.split(os.sep)
if any(fnmatch.fnmatch(rel, pat) and len(parts) == pat.count("/") + 1 for pat in GENERATED):
    print(
        f"{rel} is generated by build.py and will be overwritten on the next build. "
        "Edit build.py, pages_content.py or content-source/*.md instead, then run python3 build.py.",
        file=sys.stderr,
    )
    sys.exit(2)
